import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { Database, Globe2, Boxes, Palette, CloudCog, ArrowRight, Sparkles, Library } from 'lucide-react';

const icons = { Databases: Database, 'Web Development': Globe2, OOP: Boxes, 'Design Systems': Palette, DevOps: CloudCog };

export default function Topics() {
  const [topics, setTopics] = useState([]);
  const [mode, setMode] = useState('gemini');
  const nav = useNavigate();
  useEffect(() => { api.topics().then(setTopics); }, []);

  return <div className="page">
    <header className="page-head compact">
      <div><span className="mini-label">ASSESSMENT LIBRARY</span><h1>Choose a skill to assess.</h1><p>Choose Gemini for fresh AI-generated questions, or Built-in for the local question bank with no Gemini dependency.</p></div>
    </header>

    <div className="generator-switch card">
      <button className={mode === 'gemini' ? 'active' : ''} onClick={() => setMode('gemini')}><Sparkles size={17}/><span><b>Gemini AI</b><small>Fresh questions generated by Gemini</small></span></button>
      <button className={mode === 'local' ? 'active' : ''} onClick={() => setMode('local')}><Library size={17}/><span><b>Built-in question bank</b><small>Works without a Gemini API key</small></span></button>
    </div>

    <div className="topic-grid">{topics.map((t) => {
      const Icon = icons[t.name] || Boxes;
      return <button className="topic-card" key={t.name} onClick={() => nav(`/quiz/${encodeURIComponent(t.name)}?mode=${mode}`)}>
        <div className="topic-icon"><Icon/></div>
        <div><span className="mini-label">{t.level}</span><h3>{t.name}</h3><p>{t.description}</p></div>
        <footer><span>10 questions · {mode === 'gemini' ? 'Gemini AI' : 'Built-in'}</span><ArrowRight size={18}/></footer>
      </button>;
    })}</div>
  </div>;
}
