CREATE DATABASE IF NOT EXISTS skill_intelligence;
USE skill_intelligence;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_uuid VARCHAR(100) NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  avatar_url TEXT, city VARCHAR(100), country VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

